plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven { url 'https://maven.fabricmc.net/' }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
// o
// mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

sourceSets {
	main {
		java {
			srcDirs = ['src/main/java']
		}
		resources {
			srcDirs = ['src/main/resources']
		}
	}
}

def generatedDir = file("$buildDir/generated/modversion")

// Tarea que genera ModVersion.java con la versión del mod
task generateModVersion {
	doLast {
		def outputDir = new File(generatedDir, "com/freezecameramod/config")
		outputDir.mkdirs()
		def versionFile = new File(outputDir, "ModVersion.java")
		versionFile.text = """
            package com.freezecameramod.config;

            public class ModVersion {
                public static final String VERSION = "${project.version}";
            }
        """.stripIndent()
	}
}

// Asegura que el código generado se compile antes de compilar tu código principal
compileJava.dependsOn generateModVersion

// Incluye la carpeta generada dentro de los sources para compilar
sourceSets.main.java.srcDirs += generatedDir

// Configura el proceso de recursos para inyectar la versión en fabric.mod.json
processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}


java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from(sourceSets.main.output)

	from("src/main/resources") {
		include "**"
	}

	from("LICENSE") {
		rename { "${it}_${project.archives_base_name}" }
	}

	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	archiveClassifier.set("")
}

remapJar {
	dependsOn jar
	input.set(jar.archiveFile)
	archiveClassifier.set("")
}

tasks.build.dependsOn remapJar